Docusaurus version
WebXDAO/blockchain-dev-path pull request #38
Opened 2022-04-03 07:15 UTC by tanishqr-ck

## Related Issue

- Information about the related issue
This is the docusaurus version of devpath
Closes: #37 

### Describe the changes you've made
I have made a docusaurus version of this devpath for better readability.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update.
- [ ] This change requires a documentation update

## How Has This Been Tested?

## Checklist

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots (if applicable)

 Original           | Updated
 :--------------------: |:--------------------:
 original screenshot | updated screenshot |
 
## Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/WebXDAO/.github/blob/main/CODE_OF_CONDUCT.md)

2022-04-03 09:03 UTC, tanishqr-ck commented
Here is the preview [doc version](https://docs-sandy-one.vercel.app/)

2022-04-03 09:14 UTC, shuklaritvik06 requested changes

2022-04-03 09:14 UTC, shuklaritvik06 commented on docs/intro.md
> +Here you will learn how to become one of the Dapp Developers and collaborate with other people inside of web3community. We gather content about Blockchain developers. You don't need to see all the re
```suggestion
Here you will learn how to become one of the Dapp Developers and collaborate with other people inside of WebXDAO. We gather content about Blockchain developers. You don't need to see all the resources, but choose what content is best for you.<br />
```

2022-04-03 09:17 UTC, shuklaritvik06 approved these changes
LGTM, Awesome work! 🔥

2022-04-03 09:19 UTC, shuklaritvik06 requested changes

2022-04-03 09:19 UTC, shuklaritvik06 commented on docusaurus.config.js
> +            href:'https://github.com/WebXDAO/start-here/issues',
```suggestion
            href:'https://github.com/WebXDAO/start-here/issues/new?assignees=&labels=github-invitation&template=invitation.yml&title=Please+invite+me+to+the+community',
```

2022-04-03 11:29 UTC, AbhinavMV commented
Awesome work. 🔥
just one suggestion - in Free Training section there is just one line. maybe a link to github repo can be added(like in the readme file). or something else can be added to make it more useful.

2022-04-03 23:57 UTC, vinzvinci reviewed
Looks good, but I consider Abhinav's suggestion ☝️

2022-04-04 05:22 UTC, KukretiShubham approved these changes
LGTM, I agree to abhinav's suggestion

2022-04-05 01:59 UTC, vinzvinci commented
Hi @tanishqr-ck, is there anything you need help with?

2022-04-05 08:16 UTC, mkubdev commented
Awesome work @tanishqr-ck 💫! Merge ok ? Maybe @AbhinavMV suggestion can be done later

2022-04-05 08:31 UTC, mkubdev approved these changes
LGTM, let's ship it 💥

2022-04-05 08:32 UTC, merged

2022-04-05 08:36 UTC, vinzvinci commented
Thank you for merging and right decision. Congrats 👏